const mongoose = require("mongoose");

const caseSchema = new mongoose.Schema(
  {
    billId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Bill",
      required: true,
    },
    subContractorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "SubContractor",
      required: true,
    },
    epcId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Company",
      required: true,
    },
    cwcRfId: { type: mongoose.Schema.Types.ObjectId, ref: "CwcRf" },

    caseNumber: { type: String, unique: true },
    rmtCaseNumber: { type: String }, // RMT-CWC-XXXX format

    status: {
      type: String,
      enum: [
        "READY_FOR_COMPANY_REVIEW",
        "EPC_REJECTED",
        "EPC_VERIFIED",
        // RMT workflow statuses
        "RMT_QUEUE", // In RMT queue for processing
        "RMT_DOCUMENT_REVIEW", // RMT reviewing documents
        "RMT_PENDING_DOCS", // Waiting for missing documents
        "RMT_RISK_ANALYSIS", // Risk analysis in progress
        "RMT_APPROVED",
        "RMT_REJECTED",
        "RMT_NEEDS_REVIEW",
        "CWCAF_READY", // CWCAF generated
        // Commercial workflow
        "BID_PLACED",
        "NEGOTIATION_IN_PROGRESS",
        "COMMERCIAL_LOCKED",
        // NBFC workflow statuses
        "PENDING_NBFC_SHARE",
        "SHARED_WITH_NBFC",
        "QUOTES_RECEIVED", // NBFCs have submitted quotes
        "NBFC_SELECTED", // Seller selected an NBFC
        "NBFC_APPROVED",
        "NBFC_REJECTED",
        "MOVED_TO_NBFC_PROCESS", // Handed off to NBFC
        "ESCROW_SETUP",
        "DISBURSED",
        "COMPLETED",
        "OVERDUE",
      ],
      default: "READY_FOR_COMPANY_REVIEW",
    },

    // EPC review
    epcReviewNotes: { type: String },
    epcReviewedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    epcReviewedAt: { type: Date },

    // ========================================
    // CWCAF - CWC ANALYSIS FORM (Workflow Section 9)
    // Generated by RMT, shared with NBFCs
    // ========================================
    cwcaf: {
      // 1. Seller Profile Summary
      sellerProfileSummary: {
        businessName: String,
        constitutionType: String,
        pan: String,
        gstin: String,
        bankDetails: {
          bankName: String,
          accountNumber: String,
          ifsc: String,
        },
        kycStatus: String,
        kycCompletedAt: Date,
      },

      // 2. Buyer Approval Snapshot (from CWCRF verification)
      buyerApprovalSnapshot: {
        approvedCwcAmount: Number, // A
        repaymentTimeline: Number, // B (days)
        repaymentArrangement: {
          // C
          source: String,
          remarks: String,
        },
        verifiedBy: String,
        verifiedAt: Date,
      },

      // 3. Invoice Details
      invoiceDetails: {
        invoiceNumber: String,
        invoiceAmount: Number,
        invoiceDate: Date,
        expectedPaymentDate: Date,
        workDescription: String,
        projectName: String,
        projectLocation: String,
      },

      // 4. Risk Assessment (MVP Parameters from Workflow Section 9)
      riskAssessmentDetails: {
        // A: Buyer Credibility
        buyerCredibility: {
          companyAge: Number, // Years
          paymentTrackRecord: {
            type: String,
            enum: ["EXCELLENT", "GOOD", "AVERAGE", "POOR"],
          },
          marketReputation: {
            type: String,
            enum: ["STRONG", "MODERATE", "WEAK"],
          },
          score: Number, // 0-100
        },

        // B: Payment Dependency
        paymentDependency: {
          singleBuyer: Boolean,
          buyerCount: Number,
          concentrationRisk: {
            type: String,
            enum: ["LOW", "MEDIUM", "HIGH"],
          },
          score: Number,
        },

        // C: Invoice Aging
        invoiceAging: {
          daysSinceInvoice: Number,
          expectedPaymentDays: Number,
          agingCategory: {
            type: String,
            enum: ["FRESH", "MODERATE", "AGED"],
          },
          score: Number,
        },

        // D: Approved CWC Percentage
        approvedCwcPercentage: {
          invoiceAmount: Number,
          requestedAmount: Number,
          approvedAmount: Number,
          approvalPercentage: Number, // (approved/invoice) * 100
          gapAnalysis: String, // Notes on difference
          score: Number,
        },

        // Overall risk computation
        totalScore: Number,
        weightedScore: Number,
      },

      // Risk Category Output (Low/Medium/High)
      riskCategory: {
        type: String,
        enum: ["LOW", "MEDIUM", "HIGH"],
      },

      // 5. RMT Recommendation
      rmtRecommendation: {
        suggestedInterestRateMin: Number,
        suggestedInterestRateMax: Number,
        comments: String,
        observations: [String],
        flaggedConcerns: [String],
      },

      // 6. Gryork Disclaimer
      disclaimer: {
        text: {
          type: String,
          default:
            "Gryork provides this analysis as a facilitation tool. The final lending decision and due diligence is the sole responsibility of the NBFC partner. Gryork assumes no liability for funding decisions made based on this report.",
        },
        version: { type: String, default: "1.0" },
      },

      // Generation metadata
      generatedAt: Date,
      generatedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
      approvedAt: Date,
      approvedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" }, // RMT Head approval
    },

    // Legacy RMT Risk Assessment (keeping for backward compatibility)
    riskAssessment: {
      riskScore: { type: Number },
      riskLevel: { type: String, enum: ["low", "medium", "high", "critical"] },
      assessment: { type: String },
      recommendation: {
        type: String,
        enum: ["approve", "reject", "needs_review"],
      },
      notes: { type: String },
      assessedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
      assessedAt: { type: Date },
    },

    // Commercial lock snapshot
    commercialSnapshot: { type: mongoose.Schema.Types.Mixed },
    lockedAt: { type: Date },

    // NBFC sharing (SOP Phase 6)
    nbfcSharing: [
      {
        nbfc: { type: mongoose.Schema.Types.ObjectId, ref: "Nbfc" },
        sharedAt: { type: Date },
        sharedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
        status: {
          type: String,
          enum: [
            "PENDING",
            "QUOTED",
            "APPROVED",
            "REJECTED",
            "WITHDRAWN",
            "SELECTED",
            "NOT_SELECTED",
          ],
          default: "PENDING",
        },
        // NBFC quotation
        quotation: {
          interestRate: Number,
          tenure: Number,
          terms: String,
          remarks: String,
          quotedAt: Date,
        },
        response: {
          respondedAt: { type: Date },
          approvalDetails: {
            fundingPercentage: Number,
            interestRate: Number,
            tenorDays: Number,
          },
          rejectionReason: String,
        },
      },
    ],

    // Selected NBFC (after approval)
    selectedNbfc: { type: mongoose.Schema.Types.ObjectId, ref: "Nbfc" },

    // Transaction reference
    transactionId: { type: mongoose.Schema.Types.ObjectId, ref: "Transaction" },

    // SLA tracking reference
    slaId: { type: mongoose.Schema.Types.ObjectId, ref: "Sla" },

    // Deal value for threshold checks
    dealValue: { type: Number },
    requiresFounderApproval: { type: Boolean, default: false },

    // RMT assignment
    assignedToRmt: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    rmtAssignedAt: { type: Date },

    // Missing documents tracking (for RMT workflow)
    missingDocuments: [
      {
        documentType: String,
        requestedAt: Date,
        requestedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
        receivedAt: Date,
        notes: String,
      },
    ],

    statusHistory: [
      {
        status: String,
        changedAt: { type: Date, default: Date.now },
        changedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
        notes: String,
      },
    ],
  },
  { timestamps: true },
);

// Auto-generate case number
caseSchema.pre("save", async function () {
  if (!this.caseNumber) {
    const count = await mongoose.model("Case").countDocuments();
    this.caseNumber = `GRY-${String(count + 1).padStart(6, "0")}`;
  }
  // Generate RMT case number when entering RMT queue
  if (
    this.isModified("status") &&
    this.status === "RMT_QUEUE" &&
    !this.rmtCaseNumber
  ) {
    const rmtCount = await mongoose
      .model("Case")
      .countDocuments({ rmtCaseNumber: { $exists: true } });
    this.rmtCaseNumber = `RMT-CWC-${String(rmtCount + 1).padStart(4, "0")}`;
  }
});

// Index for efficient queries
caseSchema.index({ status: 1, assignedToRmt: 1 });
caseSchema.index({ "cwcaf.riskCategory": 1, status: 1 });
caseSchema.index({ rmtCaseNumber: 1 });

module.exports = mongoose.model("Case", caseSchema);
