const mongoose = require("mongoose");

const cwcRfSchema = new mongoose.Schema(
  {
    // Reference number for the CWCRF
    cwcRfNumber: { type: String, unique: true },

    subContractorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "SubContractor",
      required: true,
    },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    billId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Bill",
      required: true,
    },
    epcId: { type: mongoose.Schema.Types.ObjectId, ref: "Company" },

    // ========================================
    // SECTION A: Buyer & Project Details
    // ========================================
    buyerDetails: {
      buyerId: { type: mongoose.Schema.Types.ObjectId, ref: "Company" },
      buyerName: { type: String, trim: true },
      projectName: { type: String, trim: true },
      projectLocation: { type: String, trim: true },
    },

    // ========================================
    // SECTION B: Invoice Details
    // ========================================
    invoiceDetails: {
      invoiceNumber: { type: String, trim: true },
      invoiceDate: { type: Date },
      invoiceAmount: { type: Number },
      expectedPaymentDate: { type: Date },
      workDescription: { type: String, trim: true },
    },

    // ========================================
    // SECTION C: CWC Request
    // ========================================
    cwcRequest: {
      invoiceAmount: { type: Number }, // Auto-filled from invoiceDetails
      requestedAmount: { type: Number },
      requestedTenure: { type: Number }, // In days (30/45/60/90)
    },

    // ========================================
    // SECTION D: Interest Rate Preference
    // ========================================
    interestPreference: {
      preferenceType: {
        type: String,
        enum: ["RANGE", "MAX_ACCEPTABLE"],
        default: "RANGE",
      },
      minRate: { type: Number }, // Annual % (e.g., 16)
      maxRate: { type: Number }, // Annual % (e.g., 18)
      maxAcceptableRate: { type: Number }, // Alternative: "Up to X% p.a."
    },

    // ========================================
    // SELLER DECLARATION (Mandatory)
    // ========================================
    sellerDeclaration: {
      accepted: { type: Boolean, default: false },
      acceptedAt: { type: Date },
      ipAddress: { type: String },
      declarationText: {
        type: String,
        default:
          "I understand and agree that the Credit on Working Capital (CWC) availed through Gryork will be with recourse, and an escrow account will be created in my name for repayment of the facility.",
      },
    },

    // ========================================
    // BUYER (EPC) VERIFICATION - Section A, B, C
    // ========================================
    buyerVerification: {
      // A: Approved CWC Amount (Mandatory)
      approvedAmount: { type: Number },

      // B: Repayment Timeline (Mandatory) - 30/45/60/90 days
      repaymentTimeline: {
        type: Number,
        enum: [30, 45, 60, 90],
      },

      // C: Repayment Arrangement Logic (Mandatory)
      repaymentArrangement: {
        source: {
          type: String,
          enum: [
            "PAYMENT_FROM_RA_BILL",
            "PAYMENT_FROM_CLIENT_RELEASE",
            "PAYMENT_FROM_INTERNAL_TREASURY",
            "PAYMENT_FROM_RETENTION_RELEASE",
            "OTHER",
          ],
        },
        otherDetails: { type: String, trim: true }, // If source is OTHER
        remarks: { type: String, trim: true }, // Additional context
      },

      verifiedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
      verifiedAt: { type: Date },
    },

    // ========================================
    // STATUS FLOW (as per workflow document)
    // ========================================
    status: {
      type: String,
      enum: [
        "SUBMITTED", // Seller submitted CWCRF
        "KYC_REQUIRED", // KYC needs completion
        "KYC_IN_PROGRESS", // KYC chat ongoing
        "KYC_COMPLETED", // KYC verified
        "BUYER_VERIFICATION_PENDING", // Waiting for EPC verification
        "BUYER_APPROVED", // EPC verified with A, B, C
        "BUYER_REJECTED", // EPC rejected
        "UNDER_RISK_REVIEW", // RMT reviewing
        "CWCAF_READY", // CWCAF generated by RMT
        "SHARED_WITH_NBFC", // Sent to matching NBFCs
        "QUOTES_RECEIVED", // NBFCs submitted quotes
        "NBFC_SELECTED", // Seller picked an NBFC
        "MOVED_TO_NBFC_PROCESS", // Handed off to NBFC
        "ACTION_REQUIRED", // Issues need resolution
        "REJECTED", // Final rejection
        "COMPLETED", // Successfully funded
      ],
      default: "SUBMITTED",
    },

    // ========================================
    // NBFC QUOTATIONS
    // ========================================
    nbfcQuotations: [
      {
        nbfcId: { type: mongoose.Schema.Types.ObjectId, ref: "Nbfc" },
        sharedAt: { type: Date },
        quotation: {
          interestRate: { type: Number }, // Annual %
          tenure: { type: Number }, // Days
          terms: { type: String, trim: true },
          remarks: { type: String, trim: true },
        },
        quotedAt: { type: Date },
        status: {
          type: String,
          enum: ["PENDING", "QUOTED", "SELECTED", "NOT_SELECTED", "WITHDRAWN"],
          default: "PENDING",
        },
      },
    ],

    // Selected NBFC after seller choice
    selectedNbfc: {
      nbfcId: { type: mongoose.Schema.Types.ObjectId, ref: "Nbfc" },
      selectedAt: { type: Date },
      finalInterestRate: { type: Number },
      finalTenure: { type: Number },
    },

    // Platform fee
    platformFeePaid: { type: Boolean, default: false },
    platformFeeAmount: { type: Number, default: 1000 },
    paymentReference: { type: String },

    // KYC details
    kycNotes: { type: String },
    kycCompletedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    kycCompletedAt: { type: Date },

    // Case reference (when case is created from this CWCRF)
    caseId: { type: mongoose.Schema.Types.ObjectId, ref: "Case" },

    statusHistory: [
      {
        status: String,
        changedAt: { type: Date, default: Date.now },
        changedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
        notes: String,
      },
    ],
  },
  { timestamps: true },
);

// Auto-generate CWCRF number
cwcRfSchema.pre("save", async function () {
  if (!this.cwcRfNumber) {
    const count = await mongoose.model("CwcRf").countDocuments();
    this.cwcRfNumber = `CWCRF-${String(count + 1).padStart(6, "0")}`;
  }
  // Auto-fill invoice amount in CWC request
  if (this.invoiceDetails?.invoiceAmount && !this.cwcRequest?.invoiceAmount) {
    this.cwcRequest = this.cwcRequest || {};
    this.cwcRequest.invoiceAmount = this.invoiceDetails.invoiceAmount;
  }
});

// Index for efficient queries
cwcRfSchema.index({ status: 1, subContractorId: 1 });
cwcRfSchema.index({ "buyerDetails.buyerId": 1, status: 1 });
// cwcRfNumber is already indexed via unique: true in schema definition

module.exports = mongoose.model("CwcRf", cwcRfSchema);
